name: Setup nixbuild
description: Install Nix and configure nixbuild.net with GitHub OIDC
inputs:
  nixbuild_token:
    description: Attenuated nixbuild.net token for this repository
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
    - name: Configure nixbuild.net
      uses: nixbuild/nixbuild-action@dea5d365a01d55dc038487801216ea5983c8b9c8 # v26
      with:
        nixbuild_token: ${{ inputs.nixbuild_token }}
        oidc: true
