name: Setup nixbuild
description: Install Nix and configure nixbuild.net with GitHub OIDC
inputs:
  nixbuild_token:
    description: Attenuated nixbuild.net token for this repository
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
    - name: Configure nixbuild.net
      uses: nixbuild/nixbuild-action@449fa4b22e69f407614a9f448584f7ae8801334c # v24
      with:
        nixbuild_token: ${{ inputs.nixbuild_token }}
        oidc: true
