# Import-tree boundary record.
#
# flake.nix is generated by flake-file and discovers ./modules without a filter,
# so this file is no longer wiring: it records the transition's completion
# condition, which the scaffold contract asserts as an exact empty list. A
# plain-NixOS module directory placed under modules/ now fails loudly at
# discovery instead of being filtered here.
#
# Contract: tests enumerate this list; it must stay empty.
[ ]
