cloudflare:
    dns_api_token: ENC[AES256_GCM,data:ptwQKAHyijLVYhk4gfam5Mp53aQWNXFw2nugN/WO5X5OHZAoeYuLsAYF37szliN1gpgB2iA=,iv:pS/uNONiuU61vMQllsSKobwG5pfHIMgXEBkB5SqxPaw=,tag:HurRxzDN+H+oZ5zL9xiw8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUXA3a3o1UjRKU0FCaHd5
            NW8yTDBWaVRzMk96MWxCL3ZmM3RzMlpJdmtrCnRNQ25UUFNGVk54ajA5c0pDWExJ
            RzFDb3RKZ2E3WCtMYndCWXp1Uy8ySkUKLS0tIGFEUjI4d3E3MUE1Wm9lN3JIY3Nh
            a1NacnVhL1FaTWo4MWhrUnIxZTMvVUEK7QUaNfPUqdaeNoQbHW3eNGS5curgVWY8
            TAcI1a0Gco9yLwylCF6k7nkJTst1jKICsROD3QSWoqDnytclwyG5ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5asfm5rfncy4yvslj3az78kvn7hkrzq4vy0mzexf36w64a7e3nqamw3fp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMmhzeXFqdUZmdUQ4di9F
            VUd3OTdsOEFMejBFbTQrYTBnaXJZL0F3ZUNvCnVLblYybHREb2czaTZNd2FYRGI2
            UWdxNzZUU2Vxb3lXcnc5cWUyd09ETzQKLS0tIG9SckdGTE91TjB2THg1YkFlZW1y
            WVdUU1FvblA3YkJDcUJObzRLSStIblEKat269a6LLPw+0gGedH0g9JqtVXlYTklI
            f/HTASnTP5E2Vcl2w7TorThufFnKRcg6579gv72L8UwnX/XoRzh16Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lg45rhdn6mp856f97sdwxu7rpzyyz7edqwnldnpj67r6curnkqws7nn42a
    lastmodified: "2026-05-02T11:01:27Z"
    mac: ENC[AES256_GCM,data:l0nRIutWK5g0WPYaX4Ocl4I3uKs0yvYNfXCkbaU1avEiTPEIJdmzNifz8V0ZtR2s3O7/nSDa9F7vBi6cpSRtD7kCSGR4Vm0uytw7NioTJYPqofaRKYaMP6c9Jl83ttM0f05wYELompEFvKNjZwL5RUrJfo4iWa1ACAvLFn5Vcqs=,iv:5iOze4vGs90lFYisP7gHLKpt6wxNgF9pHn0Q7QwnlUQ=,tag:TFlwQJzY+hspqj6AP1SO1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
