cloudflare:
    dns_api_token: ENC[AES256_GCM,data:ptwQKAHyijLVYhk4gfam5Mp53aQWNXFw2nugN/WO5X5OHZAoeYuLsAYF37szliN1gpgB2iA=,iv:pS/uNONiuU61vMQllsSKobwG5pfHIMgXEBkB5SqxPaw=,tag:HurRxzDN+H+oZ5zL9xiw8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTWJwOGhvc3dzdzJQS1dX
            NzJHWVZHZmhscHJ2cXV6Mjh0bUhWbUVDN1VJClNDaVZhMk0zMFpHai84MFEwT1dV
            bUZLR3lVRjBVZ3dEWk45WmxlSWlFTjAKLS0tIEc1a2FlaEtPMURjYzBwZ3FsS0Jy
            WENsZ3NYTUdlVEdtcnBLTlUrSzAyMWMKoqWl2jR17M2r4HYI1o3t3ay718i/poJN
            12SsxM6gjE+6gIoYMN+vGvqGeAsgaFJrbQ1+lYD3yavP0UDPTMnn6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5asfm5rfncy4yvslj3az78kvn7hkrzq4vy0mzexf36w64a7e3nqamw3fp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZllSVUNiU24zd2wraUV4
            UUdCcFEzb3NZMDM3VGJOWElFUDhSMG90OUJ3ClJLa2l2NUFKdVNmcXlFc1diYjcx
            cmkzcG5hbTM0cmNMcmc2alhUR3F2WGMKLS0tICtXcnFKWTBMWElZak9IeUowWGRv
            RnZjOHFkck1BV1k1MWhLelA4YzFEZ0kKrhY4HJph8MxAGLV4DXB/BuCL62TzSYkv
            BHMH8HAujFnXG+CxW9UdgmGdmPMsFDuAdY+OBnsi3P9HhcPGL9mFbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16gad4zg3h8mws60nyul0eezgpn888dk0fk7v8tm4rl04tchetuzslcrgjv
    lastmodified: "2026-05-02T11:01:27Z"
    mac: ENC[AES256_GCM,data:l0nRIutWK5g0WPYaX4Ocl4I3uKs0yvYNfXCkbaU1avEiTPEIJdmzNifz8V0ZtR2s3O7/nSDa9F7vBi6cpSRtD7kCSGR4Vm0uytw7NioTJYPqofaRKYaMP6c9Jl83ttM0f05wYELompEFvKNjZwL5RUrJfo4iWa1ACAvLFn5Vcqs=,iv:5iOze4vGs90lFYisP7gHLKpt6wxNgF9pHn0Q7QwnlUQ=,tag:TFlwQJzY+hspqj6AP1SO1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
